# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projet-S4/ergonomie/test_port_c/test_c/test_c.srcs/sources_1/bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xci
# IP: The module: 'zybo_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projet-S4/ergonomie/test_port_c/test_c/test_c.srcs/sources_1/bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Projet-S4/ergonomie/test_port_c/test_c/test_c.srcs/sources_1/bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xci
# IP: The module: 'zybo_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projet-S4/ergonomie/test_port_c/test_c/test_c.srcs/sources_1/bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
