# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo/zybo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo || ORIG_REF_NAME==zybo} -quiet] -quiet

# IP: bd/zybo/ip/zybo_processing_system7_0_0/zybo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_processing_system7_0_0 || ORIG_REF_NAME==zybo_processing_system7_0_0} -quiet] -quiet

# XDC: bd/zybo/zybo_ooc.xdc
