# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.cache/wt [current_project]
set_property parent.project_path C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_output_repo c:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/sources_1/new/Add1bitA .vhd}
  {C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/sources_1/new/Add1bitB .vhd}
  {C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/sources_1/new/Add4bitsA .vhd}
  C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/sources_1/new/affhex_pmodssd.vhd
  C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/sources_1/new/synchro_module_v2.vhd
  C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/sources_1/new/Labo_adder4b_sol.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/constrs_1/new/circuit_labo_adder4b.xdc
set_property used_in_implementation false [get_files C:/ProjetsFPGA/projets_vivado/pb_APP_log_comb/pb_APP_log_comb.srcs/constrs_1/new/circuit_labo_adder4b.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top labo_adder4b_sol -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef labo_adder4b_sol.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file labo_adder4b_sol_utilization_synth.rpt -pb labo_adder4b_sol_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
